# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/Aemo-BenB.csproj'
    publishWebProjects: false
    arguments: '-p:PublishSingleFile=true --self-contained true -r linux-x64 --output $(Build.ArtifactStagingDirectory)/Aemo-BenB --no-build'
    zipAfterPublish: true

- publish: '$(Build.SourcesDirectory)/Aemo-BenB/Aemo-BenB'
  artifact: Aemo-BenB
